import type { PRContext } from "./pr-context";

export interface FormattedComment {
  header: string;
  body: string;
  footer: string;
}

/**
 * Format the generated summary as a GitHub comment
 */
export function formatSummaryComment(
  summary: string,
  prContext: PRContext,
): string {
  const header = `## 📚 Documentation Generated

Pull Request: **${prContext.title}**
Modified Files: **${prContext.modifiedFiles.length}** files

---
`;

  const footer = `

---

<details>
<summary>📋 Modified Files (${prContext.modifiedFiles.length})</summary>

${prContext.modifiedFiles.map((file) => `- \`${file}\``).join("\n")}

</details>

---

*Generated by [DXGen](https://github.com/yourusername/dxgen) - AI Documentation Agent*
`;

  return header + summary + footer;
}

/**
 * Format an error message as a GitHub comment
 */
export function formatErrorComment(
  error: Error,
  prContext: PRContext,
): string {
  return `## ⚠️ Documentation Generation Failed

Pull Request: **${prContext.title}**

**Error:**
\`\`\`
${error.message}
\`\`\`

The documentation generation process encountered an error. Please check the logs for more details.

---

*Generated by [DXGen](https://github.com/yourusername/dxgen) - AI Documentation Agent*
`;
}

